#include "legacy_world_story_vm_test_cases.hpp"

#include <filesystem>
#include <string_view>

int main(const int argument_count, char** arguments) {
    openswd3::test::Context test;
    test_default_invalid_opcode_protocol(test);
    test_shared_dialog_handler_variants(test);
    test_shared_dialog_raw_aliases(test);
    test_dialog_flag18_suppression_protocol(test);
    test_clear_dialog_control_flag(test);
    test_clear_dialog_control_flag_bit30(test);
    test_stage_dialog_lifetime(test);
    test_dialog_text_preparation_and_mode_zero_metrics(test);
    test_dialog_anchor_delay_flag_and_reset(test);
    test_dialog_checked_failure_order(test);
    test_initial_flags_and_alignment_gate(test);
    test_reinitialization_writes_only_owned_vm_fields(test);
    test_dialog_enqueue_and_wait_protocol(test);
    test_dialog_role_overlap_avoidance(test);
    test_dialog_explicit_layout_pair(test);
    test_story_transfer_protocol(test);
    test_current_map_reload_protocol(test);
    test_item_total_reload_protocol(test);
    test_mode_text_protocol(test);
    test_suspend_story_ani_protocol(test);
    test_resume_story_ani_protocol(test);
    test_gather_party_at_player_protocol(test);
    test_set_role_collision_bypass_protocol(test);
    test_enqueue_frame_deformation_protocol(test);
    test_clear_frame_execution_gate_protocol(test);
    test_party_member_field_reload_protocol(test);
    test_party_member_field_write_protocol(test);
    test_transfer_flags_and_terminal_cleanup(test);
    test_same_file_branch(test);
    test_role_action_operand_extension(test);
    test_update_role_action_fields_protocol(test);
    test_missing_role_position_patch(test);
    test_change_role_base_variant_protocol(test);
    test_change_role_variant_delta_protocol(test);
    test_set_role_position_protocol(test);
    test_step_role_protocol(test);
    test_wait_role_action_status_protocol(test);
    test_jump_same_file_offset_protocol(test);
    test_jump_if_role_path_unprepared_protocol(test);
    test_jump_if_role_path_prepared_protocol(test);
    test_role_action_chain_update_gate(test);
    test_change_requested_action_id(test);
    test_change_requested_action_id_failure_ordering(test);
    test_restore_role_action_overrides_protocol(test);
    test_start_camera_move_protocol(test);
    test_start_camera_move_failure_ordering(test);
    test_start_camera_move_window_boundaries(test);
    test_wait_for_camera_move_protocol(test);
    test_wait_for_camera_top_while_moving_protocol(test);
    test_wait_for_music_stream_transition_protocol(test);
    test_wait_for_story_video_protocol(test);
    test_latch_common_join_same_call_protocol(test);
    test_clear_common_join_latch_and_yield_protocol(test);
    test_start_frame_color_transition_protocol(test);
    test_start_frame_color_transition_window_boundaries(test);
    test_wait_for_frame_color_transition_protocol(test);
    test_suspend_story_role_protocol(test);
    test_repeat_role_action_refresh_protocol(test);
    test_shared_role_spatial_group_protocol(test);
    test_wait_for_role_action_index_threshold(test);
    test_set_next_dialog_anchor_protocol(test);
    test_step_role_list_protocol(test);
    test_secondary_role_bit30_reload_protocol(test);
    test_wait_overlay_action_lists_protocol(test);
    test_play_sound_effect_with_unread_padding_protocol(test);
    test_stage_scene_music_stream_request_protocol(test);
    test_set_music_stream_volume_protocol(test);
    test_batch_set_role_positions_protocol(test);
    test_remove_dialogs_for_role_guid_protocol(test);
    test_wait_dialog_flag_protocol(test);
    test_release_role_path_protocol(test);
    test_release_all_role_paths_protocol(test);
    test_schedule_role_paths_protocol(test);
    test_jump_if_global_bit_protocol(test);
    test_jump_if_all_global_bits_set_protocol(test);
    test_jump_if_any_global_bit_set_protocol(test);
    test_set_global_bit_protocol(test);
    test_clear_global_bit_protocol(test);
    test_reload_world_session_protocol(test);
    test_change_role_path_id_protocol(test);
    test_global_integer_protocol(test);
    test_wide_global_integer_protocol(test);
    test_set_bounded_script_clock_protocol(test);
    test_jump_if_byte_le_script_clock_protocol(test);
    test_jump_if_script_clock_exceeds_origin_delta_protocol(test);
    test_snapshot_script_clock_protocol(test);
    test_clear_role_from_scene_protocol(test);
    test_set_role_flag_8000_and_clear_one_shots_protocol(test);
    test_relocate_role_and_complete_path_protocol(test);
    test_reload_indexed_target_protocol(test);
    test_interaction_lock_protocol(test);
    test_set_role_action_wait_override_protocol(test);
    test_shared_picture_action_enqueue_protocol(test);
    test_request_battle_after_clearing_overlay_lists(test);
    test_play_sound_effect_protocol(test);
    test_shared_scene_render_control_protocol(test);
    test_write_map_role_patch_protocol(test);
    test_write_map_role_materialization_protocol(test);
    test_write_map_role_failure_ordering(test);
    test_set_selection_scroll_protocol(test);
    test_clear_selection_scroll_protocol(test);
    test_transfer_role_to_party_protocol(test);
    test_update_role_map_state_protocol(test);
    test_frame_clock_wait_protocol(test);
    test_clear_role_flag_0400_protocol(test);
    test_set_role_flag_0400_protocol(test);
    test_wait_for_frame_color_transition(test);
    test_turn_role_toward_role(test);
    test_turn_role_toward_role_lookup_boundaries(test);
    test_turn_role_toward_role_owner_and_exact_tail(test);
    test_set_role_head_sign_action(test);
    test_set_and_clear_role_wait_override(test);
    test_role_wait_override_lookup_boundaries(test);
    test_role_wait_override_exact_tails(test);
    test_clear_text_control_bit29(test);
    test_enqueue_role_head_action_protocol(test);
    test_enqueue_role_head_action_boundaries(test);
    test_dismiss_role_head_action_protocol(test);
    test_dismiss_role_head_action_boundaries(test);
    test_upsert_packed_row_effect_protocol(test);
    test_upsert_packed_row_effect_boundaries(test);
    test_control_packed_row_effect_protocol(test);
    test_control_packed_row_effect_boundaries(test);
    test_begin_story_video_protocol(test);
    test_rewrite_role_head_action_key_protocol(test);
    test_reload_random_target_protocol(test);
    test_request_battle_protocol(test);
    test_load_name_record_protocol(test);
    test_set_reserved_global_bit_protocol(test);
    test_clear_reserved_global_bit_protocol(test);
    test_set_scene_render_bit1_protocol(test);
    test_clear_scene_render_bit1_protocol(test);
    test_begin_custom_ani_protocol(test);
    test_wait_custom_ani_complete_protocol(test);
    test_consume_four_byte_noop_protocol(test);
    test_wait_custom_ani_phase_protocol(test);
    test_set_role_talk_script_protocol(test);
    test_set_role_status_bit26_protocol(test);
    test_set_role_status_from_boolean_protocol(test);
    test_set_text_layout_pair_protocol(test);
    test_clear_text_control_bit27_protocol(test);
    test_clear_text_control_bit26_protocol(test);
    test_clear_speed_mode_protocol(test);
    test_update_scene_music_table_entry_protocol(test);
    test_clear_text_control_bit25_protocol(test);
    test_append_text_allocation_protocol(test);
    test_role_base_variant_reload_protocol(test);
    test_adjust_player_item_quantity_protocol(test);
    test_item_presence_reload_protocol(test);
    test_add_party_item_if_allowed_protocol(test);
    test_swap_player_item_into_role_slot_protocol(test);
    test_request_shop_protocol(test);
    test_adjust_party_member_resources_protocol(test);
    test_reset_input_menu_state_protocol(test);
    test_stop_scene_music_stream_protocol(test);
    test_role_distance_reload_protocol(test);
    test_configure_music_stream_transition_protocol(test);
    test_initialize_primary_countdown_protocol(test);
    test_disable_primary_countdown_protocol(test);
    test_request_special_mode_four_or_five_protocol(test);
    test_set_story_flag_70_protocol(test);
    test_set_story_flag_19_protocol(test);
    test_clear_story_flag_19_protocol(test);
    test_configure_ani_follower_position_protocol(test);
    test_configure_ani_follower_target_protocol(test);
    test_wait_ani_follower_target_protocol(test);
    test_reload_current_world_session_protocol(test);
    test_reload_deferred_world_session_protocol(test);
    test_configure_deferred_world_session_protocol(test);
    test_story_file_operations_protocol(test);
    test_suppress_next_dialog_flag18_protocol(test);
    test_wait_picture_action_byte_protocol(test);
    test_enqueue_moving_action_protocol(test);
    test_enqueue_moving_action_boundaries(test);
    if (argument_count == 3 &&
        std::string_view{arguments[2]} == "initial-session") {
        test_real_new_game_story_patches_unloaded_role(
            test, std::filesystem::path{arguments[1]}
        );
    } else if (argument_count == 2) {
        const std::filesystem::path root{arguments[1]};
        test_real_clear_dialog_control_flag_record(test, root);
        test_real_change_role_base_variant_record(test, root);
        test_real_change_role_variant_delta_record(test, root);
        test_real_clear_dialog_control_flag_bit30_record(test, root);
        test_real_stage_dialog_lifetime_record(test, root);
        test_real_wait_role_action_status_record(test, root);
        test_real_story_transfer_record(test, root);
        test_real_current_map_reload_records(test, root);
        test_real_item_total_reload_records(test, root);
        test_real_mode_text_records(test, root);
        test_real_gather_party_at_player_records(test, root);
        test_real_set_role_collision_bypass_records(test, root);
        test_real_jump_same_file_offset_record(test, root);
        test_real_jump_if_role_path_unprepared_record(test, root);
        test_real_jump_if_role_path_prepared_record(test, root);
        test_real_release_role_path_record(test, root);
        test_real_release_all_role_paths_record(test, root);
        test_real_schedule_role_path_records(test, root);
        test_real_jump_if_global_bit_records(test, root);
        test_real_jump_if_all_global_bits_set_record(test, root);
        test_real_set_global_bit_record(test, root);
        test_real_clear_global_bit_record(test, root);
        test_real_reload_world_session_record(test, root);
        test_real_reload_deferred_world_session_record(test, root);
        test_real_change_role_path_id_record(test, root);
        test_real_global_integer_records(test, root);
        test_real_relocate_role_and_complete_path_record(test, root);
        test_real_reload_indexed_target_record(test, root);
        test_real_interaction_lock_records(test, root);
        test_real_set_role_action_wait_override_record(test, root);
        test_real_set_role_action_id_record(test, root);
        test_real_camera_move_records(test, root);
        test_real_wait_for_camera_move_record(test, root);
        test_real_wait_for_camera_top_while_moving_records(test, root);
        test_real_start_frame_color_transition_record(test, root);
        test_real_wait_for_frame_color_transition_record(test, root);
        test_real_repeat_role_action_refresh_record(test, root);
        test_real_shared_role_spatial_group_records(test, root);
        test_real_shared_picture_action_enqueue_records(test, root);
        test_real_play_sound_effect_records(test, root);
        test_real_shared_scene_render_control_records(test, root);
        test_real_write_map_role_record(test, root);
        test_real_set_selection_scroll_record(test, root);
        test_real_clear_selection_scroll_record(test, root);
        test_real_transfer_role_to_party_record(test, root);
        test_real_update_role_map_state_record(test, root);
        test_real_frame_clock_wait_record(test, root);
        test_real_clear_role_flag_0400_record(test, root);
        test_real_set_role_flag_0400_record(test, root);
        test_real_set_role_head_sign_record(test, root);
        test_real_clear_role_head_sign_record(test, root);
        test_real_cancel_frame_color_transition_record(test, root);
        test_real_suspend_story_role_record(test, root);
        test_real_turn_and_suspend_story_role_record(test, root);
        test_real_role_wait_override_records(test, root);
        test_real_clear_text_control_bit29_record(test, root);
        test_real_enqueue_role_head_action_records(test, root);
        test_real_dismiss_role_head_action_record(test, root);
        test_real_upsert_packed_row_effect_record(test, root);
        test_real_control_packed_row_effect_records(test, root);
        test_real_begin_story_video_records(test, root);
        test_real_wait_for_story_video_record(test, root);
        test_real_rewrite_role_head_action_key_records(test, root);
        test_real_reload_random_target_records(test, root);
        test_real_request_battle_records(test, root);
        test_real_set_scene_render_bit1_record(test, root);
        test_real_clear_scene_render_bit1_record(test, root);
        test_real_begin_custom_ani_records(test, root);
        test_real_wait_custom_ani_complete_record(test, root);
        test_real_consume_four_byte_noop_records(test, root);
        test_real_wait_custom_ani_phase_records(test, root);
        test_real_set_role_talk_script_records(test, root);
        test_real_set_role_status_bit26_records(test, root);
        test_real_set_role_status_from_boolean_records(test, root);
        test_real_set_text_layout_pair_records(test, root);
        test_real_clear_text_control_bit27_records(test, root);
        test_real_clear_text_control_bit26_records(test, root);
        test_real_clear_speed_mode_records(test, root);
        test_real_update_scene_music_table_entry_records(test, root);
        test_real_role_base_variant_reload_record(test, root);
        test_real_adjust_player_item_quantity_record(test, root);
        test_real_item_presence_reload_records(test, root);
        test_real_request_shop_record(test, root);
        test_real_adjust_party_member_resources_records(test, root);
        test_real_wait_primary_picture_action_byte_records(test, root);
        test_real_wait_role_action_index_records(test, root);
        test_real_step_role_list_records(test, root);
        test_real_secondary_role_bit30_reload_record(test, root);
        test_real_wait_overlay_action_lists_record(test, root);
        test_real_stage_scene_music_stream_request_record(test, root);
        test_real_stop_scene_music_stream_records(test, root);
        test_real_role_distance_reload_records(test, root);
        test_real_configure_music_stream_transition_records(test, root);
        test_real_initialize_primary_countdown_records(test, root);
        test_real_disable_primary_countdown_records(test, root);
        test_real_request_special_mode_four_or_five_record(test, root);
        test_real_set_story_flag_70_records(test, root);
        test_real_batch_set_role_positions_record(test, root);
        test_real_remove_dialogs_for_role_guid_records(test, root);
        test_real_wait_dialog_flag_records(test, root);
        test_real_update_role_action_fields_records(test, root);
        test_real_load_name_record_records(test, root);
        test_real_set_role_flag_8000_and_clear_one_shots_record(test, root);
        test_real_clear_role_from_scene_record(test, root);
        test_real_shared_dialog_handler_records(test, root);
        test_real_suppress_next_dialog_flag18_records(test, root);
        test_real_story_248_dialog(test, root);
        test_real_new_game_story_reaches_first_dialog(test, root);
    }
    return test.exit_code();
}
