add_library(
    openswd3_battle
    STATIC
        legacy_battle_action_dispatch.cpp
        legacy_battle_action_frame_draw.cpp
        legacy_battle_action_mode_refresh.cpp
        legacy_battle_action_summary.cpp
        legacy_battle_action_rotation_cache.cpp
        legacy_battle_actor_action_candidate_availability.cpp
        legacy_battle_actor_action_commit.cpp
        legacy_battle_actor_action_cycle.cpp
        legacy_battle_actor_action_reverse_cycle.cpp
        legacy_battle_actor_message_percent_refresh.cpp
        legacy_battle_actor_target_preparation.cpp
        legacy_battle_alternate_grid_frame.cpp
        legacy_battle_available_actor_cycle.cpp
        legacy_battle_available_actor_reverse_cycle.cpp
        legacy_battle_attack_order_dequeue.cpp
        legacy_battle_attack_order_entry.cpp
        legacy_battle_attack_order_insert.cpp
        legacy_battle_attack_order_remove.cpp
        legacy_battle_actor_retreat_ready.cpp
        legacy_battle_retreat_commit.cpp
        legacy_battle_reward_scale.cpp
        legacy_battle_actor_frame_sequence.cpp
        legacy_battle_animation_collision.cpp
        legacy_battle_actor_lifecycle.cpp
        legacy_battle_actor_list_index_commit.cpp
        legacy_battle_actor_list_query.cpp
        legacy_battle_actor_metrics.cpp
        legacy_battle_actor_priority.cpp
        legacy_battle_actor_profile_preparation.cpp
        legacy_battle_actor_progress.cpp
        legacy_battle_actor_ready.cpp
        legacy_battle_group_a_attribute_aggregation.cpp
        legacy_battle_group_a_action_execution.cpp
        legacy_battle_group_a_actor_cleanup.cpp
        legacy_battle_group_a_attribute_effect.cpp
        legacy_battle_group_a_effect_reward_application.cpp
        legacy_battle_group_a_embedded_profile_application.cpp
        legacy_battle_group_a_final_processing.cpp
        legacy_battle_group_a_configuration.cpp
        legacy_battle_group_a_growth_reward_selection.cpp
        legacy_battle_group_a_item_effect_application.cpp
        legacy_battle_group_a_npc_materialization.cpp
        legacy_battle_group_a_profile_mode_selection.cpp
        legacy_battle_group_a_resource_cleanup.cpp
        legacy_battle_group_a_resource_pair.cpp
        legacy_battle_group_a_reward_profile_application.cpp
        legacy_battle_group_a_summon_materialization.cpp
        legacy_battle_group_a_value_pair.cpp
        legacy_battle_group_a_workspace_reset.cpp
        legacy_battle_assets.cpp
        legacy_battle_background_initialization.cpp
        legacy_battle_effect_coordinator.cpp
        legacy_battle_effect_frame.cpp
        legacy_battle_effect_shift.cpp
        legacy_battle_file_lifecycle.cpp
        legacy_battle_final_actor_step.cpp
        legacy_battle_border_panel.cpp
        legacy_battle_color_accumulation.cpp
        legacy_battle_color_fade.cpp
        legacy_battle_context_prompt.cpp
        legacy_battle_control_panel_frame.cpp
        legacy_battle_debug_hotkeys.cpp
        legacy_battle_debug_overlay.cpp
        legacy_battle_debug_status_panel.cpp
        legacy_battle_defeat_panel.cpp
        legacy_battle_definition_archive.cpp
        legacy_battle_directional_scan.cpp
        legacy_battle_frame_completion.cpp
        legacy_battle_frame_coordinator.cpp
        legacy_battle_frame_effect.cpp
        legacy_battle_frame_draw.cpp
        legacy_battle_frame_refresh.cpp
        legacy_battle_full_frame_darkening.cpp
        legacy_battle_group_a_frame.cpp
        legacy_battle_group_a_target_cycle.cpp
        legacy_battle_group_b_frame.cpp
        legacy_battle_group_b_order.cpp
        legacy_battle_group_b_target_cycle.cpp
        legacy_battle_global_reset.cpp
        legacy_battle_group_effect_frame.cpp
        legacy_battle_grid_frame.cpp
        legacy_battle_growth_actor_selection.cpp
        legacy_battle_growth_caption.cpp
        legacy_battle_growth_completion_caption.cpp
        legacy_battle_growth_item_completion_panel.cpp
        legacy_battle_growth_item_result_selection.cpp
        legacy_battle_guard_panel_frame.cpp
        legacy_battle_hud_frame.cpp
        legacy_battle_image_rotation.cpp
        legacy_battle_input_dispatch.cpp
        legacy_battle_input_record_priming.cpp
        legacy_battle_frame_input_resolution.cpp
        legacy_battle_list_frame.cpp
        legacy_battle_level_advancement.cpp
        legacy_battle_level_growth_panel.cpp
        legacy_battle_level_up_panel.cpp
    legacy_battle_list_contents.cpp
        legacy_battle_menu_context_advance.cpp
        legacy_battle_menu_context_retreat.cpp
        legacy_battle_menu_input_finalize.cpp
        legacy_battle_menu_page_advance.cpp
        legacy_battle_menu_page_retreat.cpp
        legacy_battle_menu_selection_advance.cpp
        legacy_battle_menu_selection_retreat.cpp
        legacy_battle_message_phase.cpp
        legacy_battle_mode_grid_frame.cpp
        legacy_battle_narrow_grid_frame.cpp
        legacy_battle_target_selection_entry.cpp
        legacy_battle_target_selection_refresh.cpp
        legacy_battle_intensity_effect_frame.cpp
        legacy_battle_object_reset.cpp
        legacy_battle_opponent_action_dispatch.cpp
        legacy_battle_outcome_finalization.cpp
        legacy_battle_outcome_resolution.cpp
        legacy_battle_pair_transition.cpp
        legacy_battle_party_item_order.cpp
        legacy_battle_pending_action_commit.cpp
        legacy_battle_player_item_order.cpp
        legacy_battle_player_item_quantity.cpp
        legacy_battle_particle_frame.cpp
        legacy_battle_particle_spawn.cpp
        legacy_battle_post_action.cpp
        legacy_battle_pre_frame.cpp
        legacy_battle_render_geometry.cpp
        legacy_battle_reward_item_slot.cpp
        legacy_battle_runtime_shutdown.cpp
        legacy_battle_scale_fill_panel.cpp
        legacy_battle_scale_scan.cpp
        legacy_battle_script_curve.cpp
        legacy_battle_script_dispatch.cpp
        legacy_battle_selection_frame.cpp
        legacy_battle_selection_hint_frame.cpp
        legacy_battle_setup.cpp
        legacy_battle_single_effect_frame.cpp
        legacy_battle_status_indicator.cpp
        legacy_battle_startup.cpp
        legacy_battle_surface_blend.cpp
        legacy_battle_talisman_result_panel.cpp
        legacy_battle_target_ready.cpp
        legacy_battle_text_message.cpp
        legacy_battle_text_message_frame.cpp
        legacy_battle_text_panel.cpp
        legacy_battle_timing.cpp
        legacy_battle_transition.cpp
        legacy_battle_transition_control_selection.cpp
        legacy_battle_transition_stage_advance.cpp
        legacy_battle_vertical_panel.cpp
        legacy_battle_vertical_shift.cpp
        legacy_battle_victory_item_list_panel.cpp
        legacy_battle_victory_rewards.cpp
)
target_include_directories(
    openswd3_battle
    PUBLIC
        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
)
target_link_libraries(
    openswd3_battle
    PUBLIC
        openswd3_asset_runtime
        openswd3_audio_video
        openswd3_compat
        openswd3_input_time_rng
        openswd3_project_options
        openswd3_project_warnings
        openswd3_rendering
        openswd3_resource_io
        openswd3_special_modes
        openswd3_story_scene
        openswd3_world_map
)
